name: "[Reusable] Build"

on:
  workflow_call:
    inputs:
      version:
        description: "Build version (major.minor.patch, without the v)"
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2019
            vs-version: "[16.0,17.0)"
            configuration: Release-netfx3

          - os: windows-2022
            vs-version: "[17.0,)"
            configuration: Release-net6

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: ${{ matrix.vs-version }}

      - name: Build and Publish
        run:
          msbuild TimeScaleRandomizer.sln /r /p:Configuration=${{ matrix.configuration }}
          /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:Version=${{ inputs.version }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: src/bin
