name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (major.minor.patch, without the v)"
        required: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.inputs.version }}

  release:
    needs: build
    runs-on: ubuntu-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Zip artifacts
        run: |
          mkdir assets
          zip -rj assets/TimeScaleRandomizer.zip bin/mono/BepInEx
          zip -rj assets/TimeScaleRandomizer.IL2CPP.zip bin/il2cpp/BepInEx

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          body: write the changelog you lazy fuk
          draft: true
          prerelease: false
          
      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: assets
